' http://plantuml.com/activity-diagram-beta

@startuml init
!startsub BASIC

:创建Deamon进程;
note right: 用于systemctl控制

partition 检查设备信息 {
  if (已经初始化，/etc/init 存在) then (yes)
    :保证tmpfs挂载;
  else (no)
    stop
  endif
}

if (Pro 版本) then (yes)
  partition 配置网络 {
    :DisableNetworkManager;
    :DisableSystemdResolved;
    :连接初始网口;

    :添加dhcp enter hook，\
    \ndhclient调用会将DNS写入\
    \n/edge/resolv.d/dhclient.$interface;

    :设置DNSMasq 监听IP 172.18.1.1;
    :设置/etc/resolv.conf 使用dnsmasq;

    :设置/etc/dnsmasq.hosts;
    :设置docker使用dnsmasq DNS;
  }
endif

  partition 初始化 {
    if (flag --noUpdate 开启) then (no)
      :检查更新;
    endif
    :保证tmpfs挂载;
  }

!endsub
@enduml

