' http://plantuml.com/activity-diagram-beta


@startuml master
!startsub BASIC

partition "自动连接 IoTEdge Master" {
  while (edge-guard 退出) is (no)
    repeat
    :调用register接口:
    获取新的master ip
    和vpn setting;
    repeat while (master ip\n获取成功) is (no)

    :将master ip 写入\ndnsmasq.hosts;
    :reload dnsmasq;
    
    repeat
    :发送心跳;
    repeat while (心跳连接\nmaster ip\n连续掉线<5) is (yes)

    
  endwhile (yes)
  end
}

!endsub
@enduml