' http://plantuml.com/activity-diagram-beta


@startuml network
!startsub BASIC

partition 网络 {
  split
  :自动切换网口;
  end
  split again
  :DNS配置监听;
  end
  split again
  :VPN自动连接;
  end
  end split
}

!endsub
@enduml