// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package trueno

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListReply struct {
	List                 []*ModelInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetList() []*ModelInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ModelInfo struct {
	Model                string   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Version              []string `protobuf:"bytes,2,rep,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelInfo) Reset()         { *m = ModelInfo{} }
func (m *ModelInfo) String() string { return proto.CompactTextString(m) }
func (*ModelInfo) ProtoMessage()    {}
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *ModelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelInfo.Unmarshal(m, b)
}
func (m *ModelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelInfo.Marshal(b, m, deterministic)
}
func (m *ModelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelInfo.Merge(m, src)
}
func (m *ModelInfo) XXX_Size() int {
	return xxx_messageInfo_ModelInfo.Size(m)
}
func (m *ModelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ModelInfo proto.InternalMessageInfo

func (m *ModelInfo) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *ModelInfo) GetVersion() []string {
	if m != nil {
		return m.Version
	}
	return nil
}

type DistroInfo struct {
	Model                *ModelInfo `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Threshold            []float32  `protobuf:"fixed32,2,rep,packed,name=threshold,proto3" json:"threshold,omitempty"`
	Mapping              []string   `protobuf:"bytes,3,rep,name=mapping,proto3" json:"mapping,omitempty"`
	Md5                  string     `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`
	Uuid                 string     `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DistroInfo) Reset()         { *m = DistroInfo{} }
func (m *DistroInfo) String() string { return proto.CompactTextString(m) }
func (*DistroInfo) ProtoMessage()    {}
func (*DistroInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *DistroInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistroInfo.Unmarshal(m, b)
}
func (m *DistroInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistroInfo.Marshal(b, m, deterministic)
}
func (m *DistroInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistroInfo.Merge(m, src)
}
func (m *DistroInfo) XXX_Size() int {
	return xxx_messageInfo_DistroInfo.Size(m)
}
func (m *DistroInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DistroInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DistroInfo proto.InternalMessageInfo

func (m *DistroInfo) GetModel() *ModelInfo {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *DistroInfo) GetThreshold() []float32 {
	if m != nil {
		return m.Threshold
	}
	return nil
}

func (m *DistroInfo) GetMapping() []string {
	if m != nil {
		return m.Mapping
	}
	return nil
}

func (m *DistroInfo) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *DistroInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type PushRequest struct {
	Id                   uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Buffer               []byte     `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Model                *ModelInfo `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PushRequest) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *PushRequest) GetModel() *ModelInfo {
	if m != nil {
		return m.Model
	}
	return nil
}

type EvaluateRequest struct {
	Model                *ModelInfo `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Dataset              string     `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Lable                string     `protobuf:"bytes,3,opt,name=lable,proto3" json:"lable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EvaluateRequest) Reset()         { *m = EvaluateRequest{} }
func (m *EvaluateRequest) String() string { return proto.CompactTextString(m) }
func (*EvaluateRequest) ProtoMessage()    {}
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *EvaluateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateRequest.Unmarshal(m, b)
}
func (m *EvaluateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateRequest.Marshal(b, m, deterministic)
}
func (m *EvaluateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateRequest.Merge(m, src)
}
func (m *EvaluateRequest) XXX_Size() int {
	return xxx_messageInfo_EvaluateRequest.Size(m)
}
func (m *EvaluateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateRequest proto.InternalMessageInfo

func (m *EvaluateRequest) GetModel() *ModelInfo {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *EvaluateRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *EvaluateRequest) GetLable() string {
	if m != nil {
		return m.Lable
	}
	return ""
}

type EvaluateReply struct {
	Map                  float32  `protobuf:"fixed32,1,opt,name=map,proto3" json:"map,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvaluateReply) Reset()         { *m = EvaluateReply{} }
func (m *EvaluateReply) String() string { return proto.CompactTextString(m) }
func (*EvaluateReply) ProtoMessage()    {}
func (*EvaluateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *EvaluateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateReply.Unmarshal(m, b)
}
func (m *EvaluateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateReply.Marshal(b, m, deterministic)
}
func (m *EvaluateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateReply.Merge(m, src)
}
func (m *EvaluateReply) XXX_Size() int {
	return xxx_messageInfo_EvaluateReply.Size(m)
}
func (m *EvaluateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateReply.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateReply proto.InternalMessageInfo

func (m *EvaluateReply) GetMap() float32 {
	if m != nil {
		return m.Map
	}
	return 0
}

type ProgressReply struct {
	Precent              float32  `protobuf:"fixed32,1,opt,name=precent,proto3" json:"precent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProgressReply) Reset()         { *m = ProgressReply{} }
func (m *ProgressReply) String() string { return proto.CompactTextString(m) }
func (*ProgressReply) ProtoMessage()    {}
func (*ProgressReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *ProgressReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProgressReply.Unmarshal(m, b)
}
func (m *ProgressReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProgressReply.Marshal(b, m, deterministic)
}
func (m *ProgressReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProgressReply.Merge(m, src)
}
func (m *ProgressReply) XXX_Size() int {
	return xxx_messageInfo_ProgressReply.Size(m)
}
func (m *ProgressReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProgressReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProgressReply proto.InternalMessageInfo

func (m *ProgressReply) GetPrecent() float32 {
	if m != nil {
		return m.Precent
	}
	return 0
}

func init() {
	proto.RegisterType((*ListReply)(nil), "trueno.ListReply")
	proto.RegisterType((*ModelInfo)(nil), "trueno.ModelInfo")
	proto.RegisterType((*DistroInfo)(nil), "trueno.DistroInfo")
	proto.RegisterType((*PushRequest)(nil), "trueno.PushRequest")
	proto.RegisterType((*EvaluateRequest)(nil), "trueno.EvaluateRequest")
	proto.RegisterType((*EvaluateReply)(nil), "trueno.EvaluateReply")
	proto.RegisterType((*ProgressReply)(nil), "trueno.ProgressReply")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x35, 0x49, 0x3f, 0xc8, 0x6d, 0xd7, 0xdd, 0x1d, 0x45, 0x86, 0xe2, 0x43, 0x0d, 0x88, 0xf5,
	0xa5, 0x0f, 0x15, 0x11, 0x59, 0xf1, 0xc5, 0xdd, 0x87, 0x05, 0x85, 0x32, 0xbe, 0x0b, 0xe9, 0xe6,
	0x36, 0x1d, 0x99, 0xcc, 0xc4, 0xf9, 0x58, 0xf4, 0x77, 0xf8, 0x5f, 0xfc, 0x7d, 0x32, 0x33, 0x49,
	0x2a, 0xf8, 0xc1, 0xfa, 0x76, 0xcf, 0xed, 0x3d, 0xf7, 0x9c, 0x33, 0xbd, 0x81, 0x59, 0xa3, 0x2a,
	0x14, 0xeb, 0x56, 0x2b, 0xab, 0xc8, 0xc4, 0x6a, 0x87, 0x52, 0x2d, 0xe6, 0x37, 0xaa, 0x69, 0x94,
	0x8c, 0xdd, 0x62, 0x03, 0xf9, 0x7b, 0x6e, 0x2c, 0xc3, 0x56, 0x7c, 0x23, 0x4f, 0x61, 0x24, 0xb8,
	0xb1, 0x34, 0x59, 0x66, 0xab, 0xd9, 0xe6, 0x7c, 0x1d, 0x19, 0xeb, 0x0f, 0x7e, 0xcb, 0xb5, 0xdc,
	0x2b, 0x16, 0x7e, 0x2e, 0x2e, 0x20, 0x1f, 0x5a, 0xe4, 0x21, 0x8c, 0x83, 0x0a, 0x4d, 0x96, 0xc9,
	0x2a, 0x67, 0x11, 0x10, 0x0a, 0xd3, 0x5b, 0xd4, 0x86, 0x2b, 0x49, 0xd3, 0x65, 0xb6, 0xca, 0x59,
	0x0f, 0x8b, 0xef, 0x09, 0xc0, 0x25, 0x37, 0x56, 0xab, 0x40, 0x7f, 0xf6, 0x2b, 0xfd, 0x8f, 0x9a,
	0xdd, 0xc6, 0xc7, 0x90, 0xdb, 0x83, 0x46, 0x73, 0x50, 0xa2, 0x0a, 0x3b, 0x53, 0x76, 0x6c, 0x78,
	0xbd, 0xa6, 0x6c, 0x5b, 0x2e, 0x6b, 0x9a, 0x45, 0xbd, 0x0e, 0x92, 0x33, 0xc8, 0x9a, 0xea, 0x25,
	0x1d, 0x05, 0x77, 0xbe, 0x24, 0x04, 0x46, 0xce, 0xf1, 0x8a, 0x8e, 0x43, 0x2b, 0xd4, 0xc5, 0x27,
	0x98, 0x6d, 0x9d, 0x39, 0x30, 0xfc, 0xe2, 0xd0, 0x58, 0x72, 0x1f, 0x52, 0x5e, 0x05, 0x4b, 0x23,
	0x96, 0xf2, 0x8a, 0x3c, 0x82, 0xc9, 0xce, 0xed, 0xf7, 0xa8, 0x69, 0xba, 0x4c, 0x56, 0x73, 0xd6,
	0xa1, 0xa3, 0xfb, 0xec, 0xdf, 0xee, 0x8b, 0xcf, 0x70, 0x7a, 0x75, 0x5b, 0x0a, 0x57, 0x5a, 0xec,
	0x35, 0xee, 0x9c, 0x9c, 0xc2, 0xb4, 0x2a, 0x6d, 0x69, 0xd0, 0x06, 0xf5, 0x9c, 0xf5, 0xd0, 0xbf,
	0xbd, 0x28, 0x77, 0x02, 0x83, 0x7c, 0xce, 0x22, 0x28, 0x9e, 0xc0, 0xc9, 0x51, 0xcb, 0xff, 0xad,
	0xfe, 0x09, 0xca, 0x36, 0xe8, 0xa4, 0xcc, 0x97, 0xc5, 0x73, 0x38, 0xd9, 0x6a, 0x55, 0x6b, 0x34,
	0x26, 0x8e, 0x50, 0x98, 0xb6, 0x1a, 0x6f, 0x50, 0xda, 0x6e, 0xac, 0x87, 0x9b, 0x1f, 0x29, 0x8c,
	0x83, 0x25, 0x72, 0x01, 0xa7, 0xfe, 0x54, 0x3e, 0x5a, 0xa5, 0xb1, 0x8a, 0xad, 0x07, 0xbd, 0xe9,
	0x2d, 0x97, 0x75, 0x17, 0x6c, 0x31, 0x24, 0x19, 0x0e, 0xab, 0xb8, 0x47, 0xde, 0xc0, 0xd9, 0xd5,
	0xd7, 0x56, 0x69, 0x1b, 0xe3, 0x35, 0x65, 0x8d, 0xe4, 0xf7, 0xc8, 0x8b, 0x61, 0x21, 0x43, 0xe3,
	0xc4, 0xc0, 0x7e, 0x0d, 0xf3, 0x78, 0x33, 0xef, 0x94, 0xdc, 0xf3, 0x9a, 0x90, 0x7e, 0xec, 0x78,
	0x49, 0x7f, 0xa3, 0xbe, 0x85, 0xf3, 0xeb, 0x66, 0x10, 0x8e, 0xf3, 0xff, 0xc3, 0x7f, 0x05, 0xb3,
	0x4b, 0x14, 0x68, 0x31, 0x26, 0xbe, 0xb3, 0xe7, 0xdd, 0x24, 0x7c, 0x60, 0x2f, 0x7e, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x4e, 0x5e, 0xf2, 0xb2, 0x85, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModelClient is the client API for Model service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModelClient interface {
	// OnCloud
	ListStoredModel(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*ListReply, error)
	ExportModelImage(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*ResultReply, error)
	DistroConfig(ctx context.Context, in *DistroInfo, opts ...grpc.CallOption) (*ResultReply, error)
	ImportModelDistro(ctx context.Context, in *DistroInfo, opts ...grpc.CallOption) (*ResultReply, error)
	DeleteModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*ResultReply, error)
}

type modelClient struct {
	cc *grpc.ClientConn
}

func NewModelClient(cc *grpc.ClientConn) ModelClient {
	return &modelClient{cc}
}

func (c *modelClient) ListStoredModel(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/trueno.Model/ListStoredModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) ExportModelImage(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*ResultReply, error) {
	out := new(ResultReply)
	err := c.cc.Invoke(ctx, "/trueno.Model/ExportModelImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) DistroConfig(ctx context.Context, in *DistroInfo, opts ...grpc.CallOption) (*ResultReply, error) {
	out := new(ResultReply)
	err := c.cc.Invoke(ctx, "/trueno.Model/DistroConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) ImportModelDistro(ctx context.Context, in *DistroInfo, opts ...grpc.CallOption) (*ResultReply, error) {
	out := new(ResultReply)
	err := c.cc.Invoke(ctx, "/trueno.Model/ImportModelDistro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelClient) DeleteModel(ctx context.Context, in *ModelInfo, opts ...grpc.CallOption) (*ResultReply, error) {
	out := new(ResultReply)
	err := c.cc.Invoke(ctx, "/trueno.Model/DeleteModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServer is the server API for Model service.
type ModelServer interface {
	// OnCloud
	ListStoredModel(context.Context, *PingRequest) (*ListReply, error)
	ExportModelImage(context.Context, *ModelInfo) (*ResultReply, error)
	DistroConfig(context.Context, *DistroInfo) (*ResultReply, error)
	ImportModelDistro(context.Context, *DistroInfo) (*ResultReply, error)
	DeleteModel(context.Context, *ModelInfo) (*ResultReply, error)
}

// UnimplementedModelServer can be embedded to have forward compatible implementations.
type UnimplementedModelServer struct {
}

func (*UnimplementedModelServer) ListStoredModel(ctx context.Context, req *PingRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStoredModel not implemented")
}
func (*UnimplementedModelServer) ExportModelImage(ctx context.Context, req *ModelInfo) (*ResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportModelImage not implemented")
}
func (*UnimplementedModelServer) DistroConfig(ctx context.Context, req *DistroInfo) (*ResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistroConfig not implemented")
}
func (*UnimplementedModelServer) ImportModelDistro(ctx context.Context, req *DistroInfo) (*ResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportModelDistro not implemented")
}
func (*UnimplementedModelServer) DeleteModel(ctx context.Context, req *ModelInfo) (*ResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModel not implemented")
}

func RegisterModelServer(s *grpc.Server, srv ModelServer) {
	s.RegisterService(&_Model_serviceDesc, srv)
}

func _Model_ListStoredModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).ListStoredModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trueno.Model/ListStoredModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).ListStoredModel(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_ExportModelImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).ExportModelImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trueno.Model/ExportModelImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).ExportModelImage(ctx, req.(*ModelInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_DistroConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistroInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).DistroConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trueno.Model/DistroConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).DistroConfig(ctx, req.(*DistroInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_ImportModelDistro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistroInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).ImportModelDistro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trueno.Model/ImportModelDistro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).ImportModelDistro(ctx, req.(*DistroInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Model_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trueno.Model/DeleteModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServer).DeleteModel(ctx, req.(*ModelInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Model_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trueno.Model",
	HandlerType: (*ModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStoredModel",
			Handler:    _Model_ListStoredModel_Handler,
		},
		{
			MethodName: "ExportModelImage",
			Handler:    _Model_ExportModelImage_Handler,
		},
		{
			MethodName: "DistroConfig",
			Handler:    _Model_DistroConfig_Handler,
		},
		{
			MethodName: "ImportModelDistro",
			Handler:    _Model_ImportModelDistro_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _Model_DeleteModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}
