image: "golang:latest"

variables:
  GO111MODULE: "off"
  GOPROXY: "https://mirrors.aliyun.com/goproxy/"

stages:
  - build
  - deploy

build:
  cache:
    paths:
      - .cache
  stage: build
  before_script:
    # cache needs to be inside $CI_PROJECT_DIR
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"

    - export WORKDIR=$GOPATH/src/jxcore
    - mkdir -p $GOPATH/src
    - rm -rf $WORKDIR
    - ln -s $CI_PROJECT_DIR $WORKDIR
    - cd $WORKDIR
  script:
    - make clean
    - make debian arch=amd64
    - make debian arch=arm64
  artifacts:
    paths:
      - build/*
    expire_in: 1 day
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/

deploy:
  stage: deploy
  environment:
    name: package
    url: https://packages.debian.jiangxingai.com
  script:
    - make push_to_source
    
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/
