image: "golang:latest"

variables:
  GO111MODULE: "on"
  # GOPROXY: "https://mirrors.aliyun.com/goproxy/"

stages:
  - review
  - build
  - prerelease

before_script:
  - sed -i 's/http:\/\/gitlab\.jiangxingai\.com/..\/../' .gitmodules
  - git submodule sync --recursive
  - git submodule update --init --recursive

  # cache needs to be inside $CI_PROJECT_DIR
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

review:
  stage: review
  environment:
    name: develop
    url: http://10.53.1.220
  
  script:
    - make clean
    - make debian_rc arch=amd64
    - make debian_rc arch=arm64
    - make push_to_source
    - make deploy_rc
  only:
    - /^rc-/
  except:
    - branches
  
build:
  cache:
    paths:
      - .cache
  stage: build
  environment:
    name: package
    url: http://packages.debian.jiangxingai.com
  script:
    - make clean
    - make debian arch=amd64
    - make debian arch=arm64
    - make push_to_source
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/
  except:
    - branches

prerelease:
  stage: prerelease
  script:
    - make deploy_prerelease
    - make upload_changelog
  only:
    - /^v[0-9](?:\.[0-9]){2,3}/
  except:
    - branches
