#cri: true
monitor:
  telegraf: true
#devicemanagement:
#  camera: true
#  rs485: true
#  aiserving: true
tools:
  mcutools:
    watchdog: true
    mcuserver: true
  nodetools:
    #    cleaner: true
    #    usblistener: true
    filelistener: true
synctools:
  db: true
  tsdb: true
  mq: true
  fs: true
