components:
  db: true
  fs: true
  fsindex: true
  jxserving: true
  mcuserver: true
  mq: true
  powermanagerment: true
  telegraf: true
  tsdb: true
config: ""
debug: false
fixedresolver: ""
mount_cfg:
  /dev/mmcblk1p1: /media/card
no-update: false
port: :90
priority:
- eth0
- usb0
- eth1
- usb1
switch_interval: 5s
