// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages_pb3.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiskType int32

const (
	DiskType_SSD  DiskType = 0
	DiskType_HHD  DiskType = 1
	DiskType_EMMC DiskType = 2
)

var DiskType_name = map[int32]string{
	0: "SSD",
	1: "HHD",
	2: "EMMC",
}

var DiskType_value = map[string]int32{
	"SSD":  0,
	"HHD":  1,
	"EMMC": 2,
}

func (x DiskType) String() string {
	return proto.EnumName(DiskType_name, int32(x))
}

func (DiskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{0}
}

// RequireType 需要的数据包类型
type RequireType int32

const (
	// 要求设备马上上报空心跳包
	RequireType_RequireHeartBeat RequireType = 0
	// 设备 ID
	RequireType_RequireWorkerID RequireType = 1
	// CPU 信息
	RequireType_RequireCPU RequireType = 2
	// 内存信息
	RequireType_RequireMemory RequireType = 3
	// 网络信息
	RequireType_RequireNetwork RequireType = 4
	// 磁盘信息
	RequireType_RequireDisk RequireType = 5
	// 文件系统信息
	RequireType_RequireFileSystem RequireType = 6
	// 平台信息
	RequireType_RequirePlatform RequireType = 7
)

var RequireType_name = map[int32]string{
	0: "RequireHeartBeat",
	1: "RequireWorkerID",
	2: "RequireCPU",
	3: "RequireMemory",
	4: "RequireNetwork",
	5: "RequireDisk",
	6: "RequireFileSystem",
	7: "RequirePlatform",
}

var RequireType_value = map[string]int32{
	"RequireHeartBeat":  0,
	"RequireWorkerID":   1,
	"RequireCPU":        2,
	"RequireMemory":     3,
	"RequireNetwork":    4,
	"RequireDisk":       5,
	"RequireFileSystem": 6,
	"RequirePlatform":   7,
}

func (x RequireType) String() string {
	return proto.EnumName(RequireType_name, int32(x))
}

func (RequireType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{1}
}

// CPUInfo CPU 信息
type CPUInfo struct {
	Cores                uint32   `protobuf:"varint,1,opt,name=cores,proto3" json:"cores,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPUInfo) Reset()         { *m = CPUInfo{} }
func (m *CPUInfo) String() string { return proto.CompactTextString(m) }
func (*CPUInfo) ProtoMessage()    {}
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{0}
}

func (m *CPUInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPUInfo.Unmarshal(m, b)
}
func (m *CPUInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPUInfo.Marshal(b, m, deterministic)
}
func (m *CPUInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPUInfo.Merge(m, src)
}
func (m *CPUInfo) XXX_Size() int {
	return xxx_messageInfo_CPUInfo.Size(m)
}
func (m *CPUInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CPUInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CPUInfo proto.InternalMessageInfo

func (m *CPUInfo) GetCores() uint32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

// MemoryInfo 内存信息
type MemoryInfo struct {
	Capacity             uint64   `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryInfo) Reset()         { *m = MemoryInfo{} }
func (m *MemoryInfo) String() string { return proto.CompactTextString(m) }
func (*MemoryInfo) ProtoMessage()    {}
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{1}
}

func (m *MemoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryInfo.Unmarshal(m, b)
}
func (m *MemoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryInfo.Marshal(b, m, deterministic)
}
func (m *MemoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryInfo.Merge(m, src)
}
func (m *MemoryInfo) XXX_Size() int {
	return xxx_messageInfo_MemoryInfo.Size(m)
}
func (m *MemoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryInfo proto.InternalMessageInfo

func (m *MemoryInfo) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type NetworkInterface struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ipv4                 []byte   `protobuf:"bytes,2,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6                 []byte   `protobuf:"bytes,3,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Mac                  []byte   `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInterface) Reset()         { *m = NetworkInterface{} }
func (m *NetworkInterface) String() string { return proto.CompactTextString(m) }
func (*NetworkInterface) ProtoMessage()    {}
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{2}
}

func (m *NetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterface.Unmarshal(m, b)
}
func (m *NetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterface.Marshal(b, m, deterministic)
}
func (m *NetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterface.Merge(m, src)
}
func (m *NetworkInterface) XXX_Size() int {
	return xxx_messageInfo_NetworkInterface.Size(m)
}
func (m *NetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterface proto.InternalMessageInfo

func (m *NetworkInterface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkInterface) GetIpv4() []byte {
	if m != nil {
		return m.Ipv4
	}
	return nil
}

func (m *NetworkInterface) GetIpv6() []byte {
	if m != nil {
		return m.Ipv6
	}
	return nil
}

func (m *NetworkInterface) GetMac() []byte {
	if m != nil {
		return m.Mac
	}
	return nil
}

type NetworkInfo struct {
	Networks             []*NetworkInterface `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NetworkInfo) Reset()         { *m = NetworkInfo{} }
func (m *NetworkInfo) String() string { return proto.CompactTextString(m) }
func (*NetworkInfo) ProtoMessage()    {}
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{3}
}

func (m *NetworkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfo.Unmarshal(m, b)
}
func (m *NetworkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfo.Marshal(b, m, deterministic)
}
func (m *NetworkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfo.Merge(m, src)
}
func (m *NetworkInfo) XXX_Size() int {
	return xxx_messageInfo_NetworkInfo.Size(m)
}
func (m *NetworkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfo proto.InternalMessageInfo

func (m *NetworkInfo) GetNetworks() []*NetworkInterface {
	if m != nil {
		return m.Networks
	}
	return nil
}

type DiskStat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 DiskType `protobuf:"varint,2,opt,name=type,proto3,enum=rpc.edgenode.message.DiskType" json:"type,omitempty"`
	Capacity             uint64   `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskStat) Reset()         { *m = DiskStat{} }
func (m *DiskStat) String() string { return proto.CompactTextString(m) }
func (*DiskStat) ProtoMessage()    {}
func (*DiskStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{4}
}

func (m *DiskStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskStat.Unmarshal(m, b)
}
func (m *DiskStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskStat.Marshal(b, m, deterministic)
}
func (m *DiskStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskStat.Merge(m, src)
}
func (m *DiskStat) XXX_Size() int {
	return xxx_messageInfo_DiskStat.Size(m)
}
func (m *DiskStat) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskStat.DiscardUnknown(m)
}

var xxx_messageInfo_DiskStat proto.InternalMessageInfo

func (m *DiskStat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiskStat) GetType() DiskType {
	if m != nil {
		return m.Type
	}
	return DiskType_SSD
}

func (m *DiskStat) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type DiskInfo struct {
	Disks                []*DiskStat `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DiskInfo) Reset()         { *m = DiskInfo{} }
func (m *DiskInfo) String() string { return proto.CompactTextString(m) }
func (*DiskInfo) ProtoMessage()    {}
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{5}
}

func (m *DiskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskInfo.Unmarshal(m, b)
}
func (m *DiskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskInfo.Marshal(b, m, deterministic)
}
func (m *DiskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskInfo.Merge(m, src)
}
func (m *DiskInfo) XXX_Size() int {
	return xxx_messageInfo_DiskInfo.Size(m)
}
func (m *DiskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DiskInfo proto.InternalMessageInfo

func (m *DiskInfo) GetDisks() []*DiskStat {
	if m != nil {
		return m.Disks
	}
	return nil
}

type FileSystem struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	MountPath            string   `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	Capacity             uint64   `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Format               string   `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileSystem) Reset()         { *m = FileSystem{} }
func (m *FileSystem) String() string { return proto.CompactTextString(m) }
func (*FileSystem) ProtoMessage()    {}
func (*FileSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{6}
}

func (m *FileSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSystem.Unmarshal(m, b)
}
func (m *FileSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSystem.Marshal(b, m, deterministic)
}
func (m *FileSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSystem.Merge(m, src)
}
func (m *FileSystem) XXX_Size() int {
	return xxx_messageInfo_FileSystem.Size(m)
}
func (m *FileSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSystem.DiscardUnknown(m)
}

var xxx_messageInfo_FileSystem proto.InternalMessageInfo

func (m *FileSystem) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *FileSystem) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

func (m *FileSystem) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *FileSystem) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type FileSystemInfo struct {
	FileSystems          []*FileSystem `protobuf:"bytes,1,rep,name=file_systems,json=fileSystems,proto3" json:"file_systems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FileSystemInfo) Reset()         { *m = FileSystemInfo{} }
func (m *FileSystemInfo) String() string { return proto.CompactTextString(m) }
func (*FileSystemInfo) ProtoMessage()    {}
func (*FileSystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{7}
}

func (m *FileSystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSystemInfo.Unmarshal(m, b)
}
func (m *FileSystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSystemInfo.Marshal(b, m, deterministic)
}
func (m *FileSystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSystemInfo.Merge(m, src)
}
func (m *FileSystemInfo) XXX_Size() int {
	return xxx_messageInfo_FileSystemInfo.Size(m)
}
func (m *FileSystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileSystemInfo proto.InternalMessageInfo

func (m *FileSystemInfo) GetFileSystems() []*FileSystem {
	if m != nil {
		return m.FileSystems
	}
	return nil
}

// AIPlatform AI 平台信息
type AIPlatform struct {
	IncludeRknn          bool     `protobuf:"varint,1,opt,name=include_rknn,json=includeRknn,proto3" json:"include_rknn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AIPlatform) Reset()         { *m = AIPlatform{} }
func (m *AIPlatform) String() string { return proto.CompactTextString(m) }
func (*AIPlatform) ProtoMessage()    {}
func (*AIPlatform) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{8}
}

func (m *AIPlatform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AIPlatform.Unmarshal(m, b)
}
func (m *AIPlatform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AIPlatform.Marshal(b, m, deterministic)
}
func (m *AIPlatform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AIPlatform.Merge(m, src)
}
func (m *AIPlatform) XXX_Size() int {
	return xxx_messageInfo_AIPlatform.Size(m)
}
func (m *AIPlatform) XXX_DiscardUnknown() {
	xxx_messageInfo_AIPlatform.DiscardUnknown(m)
}

var xxx_messageInfo_AIPlatform proto.InternalMessageInfo

func (m *AIPlatform) GetIncludeRknn() bool {
	if m != nil {
		return m.IncludeRknn
	}
	return false
}

// PlatformInfo 数据包类型
type PlatformInfo struct {
	AiPlatform           *AIPlatform `protobuf:"bytes,1,opt,name=ai_platform,json=aiPlatform,proto3" json:"ai_platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlatformInfo) Reset()         { *m = PlatformInfo{} }
func (m *PlatformInfo) String() string { return proto.CompactTextString(m) }
func (*PlatformInfo) ProtoMessage()    {}
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{9}
}

func (m *PlatformInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInfo.Unmarshal(m, b)
}
func (m *PlatformInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInfo.Marshal(b, m, deterministic)
}
func (m *PlatformInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInfo.Merge(m, src)
}
func (m *PlatformInfo) XXX_Size() int {
	return xxx_messageInfo_PlatformInfo.Size(m)
}
func (m *PlatformInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInfo proto.InternalMessageInfo

func (m *PlatformInfo) GetAiPlatform() *AIPlatform {
	if m != nil {
		return m.AiPlatform
	}
	return nil
}

// WorkerID 设备 ID
type WorkerID struct {
	WorkerId             string   `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerID) Reset()         { *m = WorkerID{} }
func (m *WorkerID) String() string { return proto.CompactTextString(m) }
func (*WorkerID) ProtoMessage()    {}
func (*WorkerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{10}
}

func (m *WorkerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerID.Unmarshal(m, b)
}
func (m *WorkerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerID.Marshal(b, m, deterministic)
}
func (m *WorkerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerID.Merge(m, src)
}
func (m *WorkerID) XXX_Size() int {
	return xxx_messageInfo_WorkerID.Size(m)
}
func (m *WorkerID) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerID.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerID proto.InternalMessageInfo

func (m *WorkerID) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

// RequireReport 要求下级设备上报数据
type RequireReport struct {
	Requires             []RequireType `protobuf:"varint,1,rep,packed,name=requires,proto3,enum=rpc.edgenode.message.RequireType" json:"requires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RequireReport) Reset()         { *m = RequireReport{} }
func (m *RequireReport) String() string { return proto.CompactTextString(m) }
func (*RequireReport) ProtoMessage()    {}
func (*RequireReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_97c63c162ad14999, []int{11}
}

func (m *RequireReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequireReport.Unmarshal(m, b)
}
func (m *RequireReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequireReport.Marshal(b, m, deterministic)
}
func (m *RequireReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequireReport.Merge(m, src)
}
func (m *RequireReport) XXX_Size() int {
	return xxx_messageInfo_RequireReport.Size(m)
}
func (m *RequireReport) XXX_DiscardUnknown() {
	xxx_messageInfo_RequireReport.DiscardUnknown(m)
}

var xxx_messageInfo_RequireReport proto.InternalMessageInfo

func (m *RequireReport) GetRequires() []RequireType {
	if m != nil {
		return m.Requires
	}
	return nil
}

func init() {
	proto.RegisterEnum("rpc.edgenode.message.DiskType", DiskType_name, DiskType_value)
	proto.RegisterEnum("rpc.edgenode.message.RequireType", RequireType_name, RequireType_value)
	proto.RegisterType((*CPUInfo)(nil), "rpc.edgenode.message.CPUInfo")
	proto.RegisterType((*MemoryInfo)(nil), "rpc.edgenode.message.MemoryInfo")
	proto.RegisterType((*NetworkInterface)(nil), "rpc.edgenode.message.NetworkInterface")
	proto.RegisterType((*NetworkInfo)(nil), "rpc.edgenode.message.NetworkInfo")
	proto.RegisterType((*DiskStat)(nil), "rpc.edgenode.message.DiskStat")
	proto.RegisterType((*DiskInfo)(nil), "rpc.edgenode.message.DiskInfo")
	proto.RegisterType((*FileSystem)(nil), "rpc.edgenode.message.FileSystem")
	proto.RegisterType((*FileSystemInfo)(nil), "rpc.edgenode.message.FileSystemInfo")
	proto.RegisterType((*AIPlatform)(nil), "rpc.edgenode.message.AIPlatform")
	proto.RegisterType((*PlatformInfo)(nil), "rpc.edgenode.message.PlatformInfo")
	proto.RegisterType((*WorkerID)(nil), "rpc.edgenode.message.WorkerID")
	proto.RegisterType((*RequireReport)(nil), "rpc.edgenode.message.RequireReport")
}

func init() { proto.RegisterFile("messages_pb3.proto", fileDescriptor_97c63c162ad14999) }

var fileDescriptor_97c63c162ad14999 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x4f, 0x4f, 0x1b, 0x3d,
	0x10, 0xc6, 0xc9, 0x1f, 0x60, 0x33, 0x1b, 0x82, 0xf1, 0xcb, 0x5b, 0x45, 0xad, 0xda, 0xc2, 0x1e,
	0x68, 0xc4, 0x21, 0x95, 0x02, 0xe2, 0x56, 0xa9, 0x90, 0xb4, 0x22, 0x07, 0x50, 0x70, 0x8a, 0x2a,
	0xf5, 0x92, 0x9a, 0xcd, 0x2c, 0xac, 0x92, 0xb5, 0xb7, 0x5e, 0x53, 0x14, 0xa9, 0x1f, 0xa9, 0x1f,
	0xb2, 0xb2, 0xd7, 0xbb, 0xa1, 0x28, 0xe5, 0x36, 0xf3, 0xf3, 0x8c, 0xe7, 0x79, 0x26, 0xeb, 0x00,
	0x4d, 0x30, 0xcb, 0xf8, 0x2d, 0x66, 0x93, 0xf4, 0xe6, 0xa8, 0x9b, 0x2a, 0xa9, 0x25, 0xdd, 0x55,
	0x69, 0xd8, 0xc5, 0xe9, 0x2d, 0x0a, 0x39, 0xc5, 0xae, 0x2b, 0x08, 0xde, 0xc2, 0x66, 0x7f, 0x74,
	0x3d, 0x14, 0x91, 0xa4, 0xbb, 0xb0, 0x1e, 0x4a, 0x85, 0x59, 0xbb, 0xb2, 0x57, 0xe9, 0x6c, 0xb1,
	0x3c, 0x09, 0x3a, 0x00, 0x17, 0x98, 0x48, 0xb5, 0xb0, 0x35, 0x2f, 0xc1, 0x0b, 0x79, 0xca, 0xc3,
	0x58, 0x2f, 0x6c, 0x59, 0x9d, 0x95, 0x79, 0xf0, 0x1d, 0xc8, 0x25, 0xea, 0x07, 0xa9, 0x66, 0x43,
	0xa1, 0x51, 0x45, 0x3c, 0x44, 0x4a, 0xa1, 0x2e, 0x78, 0x82, 0xb6, 0xb6, 0xc1, 0x6c, 0x6c, 0x58,
	0x9c, 0xfe, 0x3c, 0x6e, 0x57, 0xf7, 0x2a, 0x9d, 0x26, 0xb3, 0xb1, 0x63, 0x27, 0xed, 0x5a, 0xc9,
	0x4e, 0x28, 0x81, 0x5a, 0xc2, 0xc3, 0x76, 0xdd, 0x22, 0x13, 0x06, 0x57, 0xe0, 0x97, 0x13, 0x22,
	0x49, 0xcf, 0xc0, 0x13, 0x79, 0x6a, 0x34, 0xd7, 0x3a, 0x7e, 0xef, 0xa0, 0xbb, 0xca, 0x64, 0xf7,
	0xa9, 0x2c, 0x56, 0xf6, 0x05, 0x02, 0xbc, 0x41, 0x9c, 0xcd, 0xc6, 0x9a, 0xeb, 0x95, 0x62, 0x7b,
	0x50, 0xd7, 0x8b, 0x14, 0xad, 0xd8, 0x56, 0xef, 0xcd, 0xea, 0xfb, 0xcd, 0x0d, 0x5f, 0x16, 0x29,
	0x32, 0x5b, 0xfb, 0xd7, 0x92, 0x6a, 0x4f, 0x96, 0xf4, 0x31, 0x9f, 0x67, 0xf5, 0x1f, 0xc3, 0xfa,
	0x34, 0xce, 0x4a, 0xf1, 0xcf, 0x5c, 0x6e, 0xe4, 0xb1, 0xbc, 0x38, 0xf8, 0x05, 0xf0, 0x39, 0x9e,
	0xe3, 0x78, 0x91, 0x69, 0x4c, 0xe8, 0x2b, 0x68, 0x44, 0xf1, 0x1c, 0x27, 0x29, 0xd7, 0x77, 0x4e,
	0xb8, 0x67, 0xc0, 0x88, 0xeb, 0x3b, 0xfa, 0x1a, 0x20, 0x91, 0xf7, 0x42, 0xe7, 0xa7, 0x55, 0x7b,
	0xda, 0xb0, 0xc4, 0x1e, 0x3f, 0xa3, 0x93, 0xbe, 0x80, 0x8d, 0x48, 0xaa, 0x84, 0x6b, 0xbb, 0xff,
	0x06, 0x73, 0x59, 0x70, 0x0d, 0xad, 0xe5, 0x74, 0xeb, 0xa2, 0x0f, 0x4d, 0xab, 0x20, 0xb3, 0xa8,
	0x30, 0xb3, 0xb7, 0xda, 0xcc, 0xb2, 0x97, 0xf9, 0x51, 0x19, 0x67, 0xc1, 0x7b, 0x80, 0xd3, 0xe1,
	0x68, 0xce, 0xb5, 0x19, 0x43, 0xf7, 0xa1, 0x19, 0x8b, 0x70, 0x7e, 0x3f, 0xc5, 0x89, 0x9a, 0x09,
	0x61, 0x7d, 0x79, 0xcc, 0x77, 0x8c, 0xcd, 0x84, 0x08, 0xae, 0xa0, 0x59, 0x94, 0x5b, 0x15, 0xa7,
	0xe0, 0xf3, 0x78, 0x92, 0x3a, 0x64, 0x3b, 0xfe, 0x29, 0x62, 0x39, 0x89, 0x01, 0x8f, 0x8b, 0x38,
	0x78, 0x07, 0xde, 0x57, 0xa9, 0x66, 0xa8, 0x86, 0x03, 0xb3, 0xd6, 0x07, 0x1b, 0x4f, 0xe2, 0x69,
	0xb1, 0xd6, 0x1c, 0x0c, 0xa7, 0xc1, 0x25, 0x6c, 0x31, 0xfc, 0x71, 0x1f, 0x2b, 0x64, 0x98, 0x4a,
	0xa5, 0xe9, 0x07, 0xf0, 0x54, 0x0e, 0x72, 0xfb, 0xad, 0xde, 0xfe, 0xea, 0xc9, 0xae, 0xcd, 0x7e,
	0x2b, 0x65, 0xcb, 0xe1, 0x41, 0xfe, 0x4d, 0x18, 0x4a, 0x37, 0xa1, 0x36, 0x1e, 0x0f, 0xc8, 0x9a,
	0x09, 0xce, 0xcf, 0x07, 0xa4, 0x42, 0x3d, 0xa8, 0x7f, 0xba, 0xb8, 0xe8, 0x93, 0xea, 0xe1, 0xef,
	0x0a, 0xf8, 0x8f, 0x6e, 0xa0, 0xbb, 0x40, 0x5c, 0x7a, 0x8e, 0x5c, 0xe9, 0x33, 0xe4, 0x9a, 0xac,
	0xd1, 0xff, 0x60, 0xdb, 0xd1, 0xc2, 0x0d, 0xa9, 0xd0, 0x16, 0x80, 0x83, 0xfd, 0xd1, 0x35, 0xa9,
	0xd2, 0x9d, 0xd2, 0x42, 0xfe, 0xb8, 0x49, 0x8d, 0x52, 0x68, 0x39, 0xe4, 0x9e, 0x0b, 0xa9, 0xd3,
	0xed, 0x72, 0xa0, 0x11, 0x48, 0xd6, 0xe9, 0xff, 0xb0, 0xe3, 0xc0, 0xf2, 0x97, 0x24, 0x1b, 0x8f,
	0x66, 0x16, 0xdb, 0x24, 0x9b, 0x67, 0xfe, 0xb7, 0xc6, 0x9d, 0xd1, 0x75, 0x83, 0x5c, 0xdf, 0x6c,
	0xd8, 0x3f, 0xa1, 0xa3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xe0, 0x8d, 0x1f, 0x9a, 0x04,
	0x00, 0x00,
}
