package supervisor

const (
	SupervisorHost = "127.0.0.1"
)

var supervisorMethodNames = []string{
	"supervisor.addProcessGroup",
	"supervisor.clearAllProcessLogs",
	"supervisor.clearLog",
	"supervisor.clearProcessLog",
	"supervisor.clearProcessLogs",
	"supervisor.getAPIVersion",
	"supervisor.getAllConfigInfo",
	"supervisor.getAllProcessInfo",
	"supervisor.getIdentification",
	"supervisor.getPID",
	"supervisor.getProcessInfo",
	"supervisor.getState",
	"supervisor.getSupervisorVersion",
	"supervisor.getVersion",
	"supervisor.readLog",
	"supervisor.readMainLog",
	"supervisor.readProcessLog",
	"supervisor.readProcessStderrLog",
	"supervisor.readProcessStdoutLog",
	"supervisor.reloadConfig",
	"supervisor.removeProcessGroup",
	"supervisor.restart",
	"supervisor.sendProcessStdin",
	"supervisor.sendRemoteCommEvent",
	"supervisor.shutdown",
	"supervisor.signalAllProcesses",
	"supervisor.signalProcess",
	"supervisor.signalProcessGroup",
	"supervisor.startAllProcesses",
	"supervisor.startProcess",
	"supervisor.startProcessGroup",
	"supervisor.stopAllProcesses",
	"supervisor.stopProcess",
	"supervisor.stopProcessGroup",
	"supervisor.tailProcessLog",
	"supervisor.tailProcessStderrLog",
	"supervisor.tailProcessStdoutLog",
	// "system.listMethods",
	// "system.methodHelp",
	// "system.methodSignature",
	// "system.multicall",
}
